### ISSUE TITLE
DotNet - Implementación checkout 2 medios de pago

### ISSUE THREAD

**Issue by RodrigoCalvo** [mercadopago/sdk-dotnet#12]
Les comento que tenemos varios sitios de e-commerce utilizando la API de DotNet provista por MP.

Estamos intentando implementar la nueva funcionalidad del procesador de pagos: checkout con 2 medios de pago. Debido a la poca documentación estamos fallando en nuestra tarea. 

¿Qué es lo qué debemos hacer? ¿Cambia el JSON que le envíamos a la plataforma?¿Cambian las notificaciones que nos envían?

Aguardo comentarios. Saludos!

**Comment by joelibaceta** [comment]
@RodrigoCalvo este no es un canal de soporte, esta destinado únicamente al reporte sobre bugs en el SDK Legacy para PHP.
