### ISSUE TITLE
.Net Core 2.0+ Issue

### ISSUE THREAD

**Issue by axelesp** [mercadopago/sdk-dotnet#139]
En una aplicación .Net Core 2.2 no se puede leer los métodos del sdk v2.0.0 de MercadoPago:
TypeLoadException: Could not load type 'MercadoPagoConfig.AccessToken' from assembly 'mercadopago, Version=0.3.3.0, Culture=neutral, PublicKeyToken=null'.
TypeLoadException: Could not load type 'MercadoPago.Client.Preference.PreferenceRequest' from assembly 'mercadopago, Version=0.3.3.0, Culture=neutral, PublicKeyToken=null'.

**Comment by delias-silva** [comment]
Hello @axelesp!

Thank you for your collaboration!

For a better analysis of the problem, could you give more information about your development environment and add snippets of your code and .csproj?

**Comment by axelesp** [comment]
Sure, I develop a plugin for the NopCommerce 4.1 platform on Framework Net Core 2.2 MVC pattern. Particularly the call to mercadopago sdk from an 'ActionResult' method inside a controller. 

`using MercadoPago.Config;
using MercadoPago.Client.Preference;
using MercadoPago.Resource.Preference;
...
private object[] CreatePreference()
        {
            object[] oReturn = new object[2];
          
            // Add Access token
            MercadoPago.Config.MercadoPagoConfig.AccessToken = mpPaymentSettings.accessToken;

            // Create preference request
            var request = new PreferenceRequest
            {
                Items = new List<PreferenceItemRequest>
                {
                    new PreferenceItemRequest
                    {
                        Title = "Sale Product in Store",
                        Quantity = 1,
                        CurrencyId = "MXN",
                        UnitPrice = 857.90m,
                    },
                },
            };

            // Create client preference
            var client = new PreferenceClient();

            //Preference preference = await client.CreateAsync(request);
            Preference preference = client.Create(request);

            oReturn[1] = preference.Id;
            oReturn[2] = preference.InitPoint;

            return oReturn;
        }
public ActionResult ActionProccessMP()
        {
            
            object[] oPref = CreatePreference();

            ProcessMPModel processMpModel = new ProcessMPModel();
...}`

Removing the 'using ...' and placing the call to the sdk directly when using it also returns the same result, it does not even manage to enter the Method, it seems that the precompile analysis detects the problem.

**Comment by romerosilva-meli** [comment]
Hey @axelesp,

it could be an issue in the way your local environment is trying to load the SDK. Check [this SO question](https://stackoverflow.com/questions/124841/could-not-load-type-from-assembly-error) and see if any of the answers help.

**Comment by axelesp** [comment]
Another project in the same solution has the old Mercadopago.dll v0.3.3 library, although there is no reference to that project, I don't understand why it was pulling that one. I copied the v2.0.0 library to the project's root directory and referenced it from there and it worked.
But now in:

```
. . .
var client = new MercadoPago.Client.Preference.PreferenceClient();
MercadoPago.Resource.Preference.Preference preference = client.Create(request); <- Exception
```
![MPProjDep](https://user-images.githubusercontent.com/69184580/128781300-22aab100-fc25-4eb4-8c79-89f2792130f0.JPG)
It throws me: 
FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. El sistema no puede encontrar el archivo especificado.

ConfigurationManager is in the Nuget package but it says v4.5.0.

**Comment by romerosilva-meli** [comment]
It could be a conflict of package versions, since it's trying to load version 4.0.1.0 and you said you have version 4.5.0. Is there any other projects in your solution using v4.0.1.0?

**Comment by axelesp** [comment]
No, there is another one that uses 'System.Configuration.dll' with version 4.6.2711

**Comment by romerosilva-meli** [comment]
Since this issue doesn't seem related to the SDK, we suggest you contact our support team at developers.mercadopago.com for further assistance.

Thanks.
