### ISSUE TITLE
Interfaces para permitir pruebas unitarias

### ISSUE THREAD

**Issue by CristianBazaesNubox** [mercadopago/sdk-dotnet#141]
**Is your feature request related to a problem? Please describe.**
Estoy trabajando en una integración con MercadoPago utilizando esta librería y a la hora de realizar pruebas unitarias me encuentro que no tengo interfaces para poder crear implementaciones mock.

**Describe the solution you'd like**
Sería genial contar con un set de interfaces que permitan crear mocks de los clientes que permiten interactuar con las API de MercadoPago.

**Describe alternatives you've considered**

**Additional context**

**Comment by delias-silva** [comment]
Hola @CristianBazaesNubox! Como estás?

Gracias por tu contribución.

Vamos a mirar este punto de posibilitar crear un mock de nuestro SDK en futuros releases.
Pero como usamos las issues acá más para hacer track de los bugs del SDK, voy a cerrar esta issue.
Para este tema puedes abrir una [discussion](https://github.com/mercadopago/sdk-dotnet/discussions/new)? Ahí contestamos por allá y te actualizamos con las novedades.

Saludos.

**Comment by CristianBazaesNubox** [comment]
Hecho, muy agradecido por tu respuesta.
