### ISSUE TITLE
Sugerencia: Usar decimal en lugar de float para valores monetarios

### ISSUE THREAD

**Issue by fberasategui** [mercadopago/sdk-dotnet#48]
En general se desalienta el uso de `float` para valores monetarios.

https://stackoverflow.com/a/3730040/643085

https://husobee.github.io/money/float/2016/09/23/never-use-floats-for-currency.html

Sugiero reemplazar este tipo por `decimal` en todo el SDK, siempre que se trate de valores monetarios.

Si están de acuerdo levanto un PR con este cambio.

**Comment by joelibaceta** [comment]
@fberasategui Nos parece una buena sugerencia para valores monetarios, esperamos el PR y una nota del cambio en el `Changelog` ya que este cambio puede requerir cambios para alguien que cambie de la versión anterior a la nueva.
