### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by joelibaceta** [mercadopago/sdk-dotnet#51]

**Comment by MercadoPagoDevelopers** [comment]
Hi,

First of all, we would like to give our sincere apologies for our belated answer.

Secondly, we are happy to announce the brand new SDK, which includes most of the suggestions that the community made in this repository. Therefore, all the existing issues and pull requests will be closed.

We are continuously working to keep our code up to date and communicating to you the latest news.

We hope to receive your comments, issues and contributions to keep moving our product to the next level.

Thanks.
The Mercado Pago Developers team.
