### ISSUE TITLE
MPRESTException: The underlying connection was closed

### ISSUE THREAD

**Issue by elarrat** [mercadopago/sdk-dotnet#61]
I'm trying to create a simple payment after getting the card's token:

            var payment = new Payment
            {
                TransactionAmount = 100,
                Token = token,
                Description = "Yadayadayada",
                ExternalReference = "15",
                PaymentMethodId = typeId,
                Installments = 1,
                Payer = new Payer
                {
                    Email = "Jon Doe",
                    FirstName = "Jon",
                    LastName = "Doe"
                },
            };

But I keep getting the exception "MPRESTException: The underlying connection was closed". Am I doing anything wrong?

**Comment by fberasategui** [comment]
@elarrat you might be hitting [TLS](http://beta.mercadopago.com.ar/developers/es/guides/pci-compliant-merchants/disabling-tls-10) issues. Please follow that link for instructions on how to fix this issue.

**Comment by nataliacorinadiaz** [comment]
Buenas! yo tengo el mismo problema, verifique la version de .net y es 4.7.1, con lo cual se supone que soporta TLS 1.2 o posteriores por defecto... que otra cosa puede estar pasando?

**Comment by fberasategui** [comment]
@nataliacorinadiaz en qué OS estás corriendo? fijate que el proyecto "principal" de tu solución (por ejemplo si estás usando ASP.NET MVC tiene que ser el proyecto que contiene las vistas y los controllers) compile contra la versión correcta de .NET.

**Comment by nataliacorinadiaz** [comment]
Gracias @fberasategui por responder!!!
Estoy trabajando con una ASP.NET Web API, compila contra .net framework 4.7.1
En el server hay windows server 2016 (el notification-url apunta a la version subida al server)
En mi maquina de desarrollo tengo windows 10
Como yo no me encargo de la parte del front (y tampoco entiendo mucho de eso) cree una aplicacion asp.net solo para agregar el boton para levantar la intefaz (tal cual muestran en el ejemplo de MP) y conseguir el token cargando los datos de prueba. Aca tambien  contra .net framework 4.7.1

**Comment by fberasategui** [comment]
@nataliacorinadiaz raro...

Probá agregando esta línea *antes* de hacer la invocación a MP...

```csharp
ServicePointManager.SecurityProtocol |= (SecurityProtocolType)3072;
```

**Comment by nataliacorinadiaz** [comment]
no... no me funciono...
a mi este error me daba en la llamada que MP realiza con las notificaciones de pago, cuando intento hacer el get by id. Pero me di cuenta hace un ratito que en realidad las notificaciones que estoy recibiendo no son por los pagos de prueba que realizo con mi sistema, sino que me esta enviando notificaiones cuando configuro la URL de notificaciones en mi cuenta. No se si esto tendra algo que ver, hace tantos dias que peleo con esta integración que ya no estoy segura de nada. Cuando vi esto publique otra consulta con el codigo para ver si estoy comprendiendo bien como deberia recibir notificaciones.
Te agradezco por las respuestas @fberasategui !

**Comment by fberasategui** [comment]
@nataliacorinadiaz tal vez si posteás el detalle de la excepción te puedo ayudar mejor. La clase `MPIPN` tiene algunos bugs y no funciona muy bien.

Yo he levantado PRs para arreglarlo pero no he tenido respuesta.

Si no encontrás alternativa, te invito a probar nuestra versión extraoficial del SDK: https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk

Al menos si tenés un issue te podemos dar una respuesta ;), versus el silencio total que hay por parte de los maintainers del SDK oficial =(

**Comment by elarrat** [comment]
In my case, the link provided did the trick. BTW, I forgot to thank fberasategui for it. Thanks a million!

**Comment by srochacito** [comment]
Tengo el mismo problema que se describe al inicio de este issue. Ya intenté todo lo que aquí se menciona y no logro echarlo a andar.

1. Cambié a .net 4.7
2. Agregué el código para checar la seguridad y no corre.
3. Agregué ServicePointManager.SecurityProtocol |= (SecurityProtocolType)3072;

Sistema operativo Windows 10.

Lo único que no hice fué usar el paquete de Lexim soluciones.
 
¿Qué más se puede hacer?

**Comment by MercadoPagoDevelopers** [comment]
Hi,

First of all, we would like to give our sincere apologies for our belated answer.

Secondly, we are happy to announce the brand new SDK, which includes most of the suggestions that the community made in this repository. Therefore, all the existing issues and pull requests will be closed.

We are continuously working to keep our code up to date and communicating to you the latest news.

We hope to receive your comments, issues and contributions to keep moving our product to the next level.

Thanks.
The Mercado Pago Developers team.
