### ISSUE TITLE
Error al cargar MerchantOrder con Load (configuración incorrecta del endpoint)

### ISSUE THREAD

**Issue by fernandezja** [mercadopago/sdk-dotnet#62]
Al intentar obtener un MerchantOrder da error 404.
Lo que vemos es que esta configurado para [GETEndpoint("/merchant_order/:id")] y deberia ser el endpoint de la api a "/merchant_orders/:id" (falta una s)

Para reproducir
`   var merchantOrder = new MercadoPago.Resources.MerchantOrder();
var orden = merchantOrder.Load(ordenId)`

![image](https://user-images.githubusercontent.com/201305/44608415-0130ae00-a7ca-11e8-836a-592b976e1a7a.png)

**Comment by fberasategui** [comment]
@joelibaceta corregido en https://github.com/mercadopago/dx-dotnet/pull/55.

Es importante remarcar que no hay Unit Tests para las clases de Merchant Order.

**Comment by fberasategui** [comment]
@fernandezja ante la falta de respuesta de la gente de MP, nosotros hemos publicado una versión extraoficial:

https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk

ya está disponible en Nuget para descargar.

Este issue está resuelto en nuestra versión.

Saludos

**Comment by diegocofre** [comment]
tengo un fix para MerchanOrderTest. Si me habilitan lo pusheo a un branch

**Comment by joelibaceta** [comment]
@diegocofre entiendo que ambos proyectos son públicos, podrías realizar un PR a partir de un branch personal siempre.

**Comment by mrdemarchi** [comment]
Los endpoint quedaron corregidos.
