### ISSUE TITLE
El authorization_code es el "codigo de autorizacion" del cupon emitido por la tarjeta?

### ISSUE THREAD

**Issue by jacargentina** [mercadopago/sdk-dotnet#66]
La documentacion es bastante vaga al respecto, además la llamada mediante `Payment.Search` no devuelve dicho campo; solo es visible si utilizo la libreria nodejs

**Comment by jacargentina** [comment]
Algún avance?

**Comment by MercadoPagoDevelopers** [comment]
Hola @jacargentina,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
