### ISSUE TITLE
Error al buscar payment por id en Resources.Payment.FindById("payment_id")

### ISSUE THREAD

**Issue by mg9101** [mercadopago/sdk-dotnet#71]
El error se da cuando se quiere buscar un pago por id, el código es el siguiente

                If MercadoPago.SDK.ClientId = "" Then
                    MercadoPago.SDK.ClientId = "client_id"
                    MercadoPago.SDK.ClientSecret = "client_secret"
                End If
                Dim payment1 As New MercadoPago.Resources.Payment
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
                payment1 = MercadoPago.Resources.Payment.FindById(Request.QueryString("collection_id"))

El error salta en la linea:
                payment1 = MercadoPago.Resources.Payment.FindById(Request.QueryString("collection_id"))

Localmente funciona perfecto, cuando lo subimos al sitio tira el siguiente error:

**No se puede convertir un objeto de tipo '_ClassName' al tipo 'MercadoPago.Resources.Payment'.**

Donde _ClassName es el nombre de la clase donde se esta ejecutando el código: 
Partial Class _ClassName

Para solucionar el problema tuvimos que usar la versión no oficial de Lexim, en esta funciona perfecto.

**Comment by MercadoPagoDevelopers** [comment]
Hola @mg9101,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
