### ISSUE TITLE
Código de error inaccesible desde Payment cuando se genera error 400

### ISSUE THREAD

**Issue by nsabaj95** [mercadopago/sdk-dotnet#75]
**Describe the bug**
Al realizar un pago y tras producirse BadParamsError, no es posible obtener el código de error a menos que se castee el campo Errors de tipo RecuperableError a BadParamsError lo cual es muy poco intuitivo. Esto ocurre ya que la propiedad Cause no es parte de RecuperableError.

**To Reproduce**
1. Generar un pago con código 400. Por ejemplo, pagando con el mail del vendedor a fin de lanzar "Invalid users involved".
2. Intentar obtener el código de error utilizando el campo Errors de Payment.

**Expected behavior**
Se espera poder acceder al código de error generado sin necesidad de hacer casteos de por medio que requieran también analizar el tipo de implementación que se haga con RecuperableError. Por ejemplo, si surge un error 400, me gustaría poder obtener el código de error de la siguiente manera: payment.Errors.Cause.Code.

**Comment by nsabaj95** [comment]
@joelibaceta El problema es que no nos dan oportunidad de modificar los mensajes de error ni el idioma en que se emiten los mismos. En este momento estamos lidiando con el error "Invalid users involved" el cual no describe su significado real. Se supone que este error se lanza cuando se intenta pagar con un email de Mercado Pago que pertenece a un usuario de un país diferente al del vendedor, por ende con el texto "Invalid users involved" no damos ninguna información.

Espero feedback por este tema. 

La versión que estamos utilizando es la 1.0.41.

**Comment by joelibaceta** [comment]
@fberasategui el 401 es un error http generico, me refería a que reservamos muchos errores de tipo 400 para errores recuperables de MercadoPago, con un código interno en las causas, como código de moneda no soportado o token invalido, esto no siempre debe traducirse en un mensaje al usuario final.

Estamos revisando el escenario de errores ya que esperamos mantener un mismo formato de exploración de errores recuperables cross-tecnologia.

@nsabaj95 revisaremos la clase de causas de error RecuperableErrorCause, la cual debería indicarte el código de error.

**Comment by fberasategui** [comment]
@joelibaceta Sigue sin ser muy claro el concepto de "error recuperable". En cualquier caso como dije se está dejando al consumidor la responsabilidad de poner todo el tiempo código del estilo `if (resource.Errors.Message != null)` o algo por el estilo **además** del try/catch que se debe usar para errores que si generan exception. Si el consumidor "se olvida" de poner ese if va a haber casos de fallas que no se van a detectar.

Fijate [el ejemplo](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk/blob/master/MercadoPagoSDK.Samples/Samples/ExceptionSample.cs#L19) de cómo manejar errores en el SDK nuestro, que mantiene la consistencia, y elimina la posibilidad de errores silenciosos.

Otra cosa: si hay una lista de códigos internos de causas de error, estaría bueno tener acceso, para generar un `enum` con todos los posibles códigos y permitir que el consumidor decida a partir de eso qué acción tomar, o qué mensaje puntual o localizado mostrar al usuario, etc.

**Comment by fberasategui** [comment]
@joelibaceta Otra cosa más: entiendo la idea de mantener un mismo approach cross-tecnología, pero no la comparto. Caés en el "lowest common denominator", ya que por ejemplo si en C# tuvieramos que mantener los mismos approaches que se usan en java estaríamos usando una versión de C# hace 15 años.

**Comment by fberasategui** [comment]
@joelibaceta [acá](https://groups.google.com/forum/#!category-topic/mercadopago-developers/sdks/_7QqKXmH5Bw) tenés otro caso. Usando la ultima versión, la API está devolviendo esto:

```json
{"message":"Oops! Something went wrong...","error":"internal_error","status":500,"cause":[]}
```

con HTTP Status 500, con lo cuál el código entra por [acá](https://github.com/mercadopago/dx-dotnet/blob/master/px-dotnet/Core/MPBase.cs#L272) y falla de manera silenciosa.

Si este comportamiento es intencional se debería documentar, ya que va contra el [principio de no WTFs](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) y es totalmente contraintuitivo.

**Comment by joelibaceta** [comment]
@fberasategui efectivamente, el enfoque de tratar de mantener una misma interfaz hacia el usuario final tiene como fin poder contar una única historia cross-tecnologia, lo cual no significa realizar implementaciones no idiomáticas.

**Comment by joelibaceta** [comment]
@nsabaj95 A partir de la versión 1.0.53 puedes consultar las causas de la siguiente manera:

**Comment by fberasategui** [comment]
@joelibaceta el problema con eso, como dije, es que caes en el lowest common denominator. 

Yo sigo sin entender a qué se refiere el término "error recuperable". Qué diferencia hay entre un error recuperable y uno que no lo es? Por qué en un caso la responsabilidad de determinar si existe error o no está del lado del consumidor, mientras que en el otro se utilizan mecanismos idiomáticos (exceptions)?

Otra cosa, en el ejemplo de arriba, si el array tiene cero elementos usar `[0]` te da un exception. La forma idiomática en C# es `payment.Errors?.Cause?.FirstOrDefault()?.Code` ya que nadie me garantiza que alguno de los objetos de la cadena no es null.

**Comment by joelibaceta** [comment]
@fberasategui Error recuperable corresponde a una agrupación de errores interna, en resumen, son errores producidos por el integrador, los errores no recuperables son errores producidos por algún componente, API o Aplicación interna de MercadoPago.

**Comment by fberasategui** [comment]
@joelibaceta o sea que se espera que el consumidor (integrador) valide que la propiedad `Errors` no sea null despues de cada llamada a metodos effectful?

Lo primero que va a pasar es que toda la gente va a hacer esto:

```csharp
public static T TryInvoke<T>(this T resource, Action<T> action)
{
    action(resource);
    if (resource.Errors != null)
        throw new Exception(resource.Errors.Message);
}
```

Y va a crear una abstracción encima de la abstracción (que es el SDK), ya que esta última está insuficientemente abstraida.

**Comment by joelibaceta** [comment]
@fberasategui Estamos trabajando en un retorno booleano para métodos como **save** y **update**

```csharp
if ( payment.save() ) {
  // Si se creo correctamente el pago 
} else {
  // Si hubo un error pueden consultar el atributo Errors
}
```

**Comment by fberasategui** [comment]
@joelibaceta No me parece una buena solución en lo más mínimo.

1 - No soluciona el problema planteado en mi comentario anterior. Esto deja librado al consumidor la responsabilidad de verificar si el resultado es `true` o `false`.

2 - Sigo sin entender cómo se espera que el user code responda ante una respuesta errónea, y por qué ésta sería distinta de las "otras" respuestas erróneas que sí producen un exception. El tema de la "agrupación de errores interna" me parece un implementation detail que nada tiene que ver con el user code de los que consumimos el SDK.

3 - Como dije en el comment en el commit, esto rompe el 100% del user code existente:
  - Si se usó `var result = payment.Save()`, ahora está fallando de forma silenciosa y no hay nada que le diga al consumidor que tiene que validar el resultado booleano.
  - Si se usó `Payment result = payment.Save()`, ahora ese código ya no compila y es una experiencia de usuario horrible actualizar un `minor` un paquete y que rompa por todos lados.
  - Si se usó `payment.Save()` ahora está fallando de manera silenciosa.

4 - 

```csharp
public static T TryInvoke<T>(this T resource, Func<T, bool> action) where T: MPBase
{
   var result = action(resource);
    if (!result)
        throw new Exception(resource.Errors.Message);
    return resource;
}
```

**Comment by MercadoPagoDevelopers** [comment]
Hola,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
