### ISSUE TITLE
Error al pagar utilizando MarketplaceAccessToken

### ISSUE THREAD

**Issue by nsabaj95** [mercadopago/sdk-dotnet#76]
**Describe the bug**
Al pagar utilizando MarketplaceAccessToken se lanza error informando que el campo marketplace_access_token es inválido, lo cual tiene sentido ya que la api no trabaja con este campo. Entiendo que el problema es que cuando se asigna la propiedad MarketplaceAccessToken de un objeto Payment, el SDK intenta enviar el valor del mismo en un campo marketplace_access_token el cual para la API no existe.

**To Reproduce**
1. Crear un objeto Payment 
2. Asignar MarketplaceAccessToken
3. Pagar

**Expected behavior**
Crear un pago haciendo uso del Access Token especificado en el campo MarketplaceAccessToken

Probado en versión 1.0.52

**Comment by joelibaceta** [comment]
@nsabaj95 revisaremos el error, te explico el funcionamiento, el campo MarketplaceAccessToken permite definir un AccessToken que se usara para realizar requests a los APIs para una instancia en particular, por lo general útil en escenarios Marketplace en el que debes usar el accesstoken del vendedor generado para crear un pago o una preferencia.

**Comment by nsabaj95** [comment]
@joelibaceta Perfecto! Si, sabía del funcionamiento. El problema es que está ocurriendo ese error que reporté por ende no pude probar el funcionamiento.

**Comment by nsabaj95** [comment]
Alguna novedad con este tema?

**Comment by nsabaj95** [comment]
@joelibaceta pudieron resolver este error?

**Comment by joelibaceta** [comment]
@nsabaj95 actualmente solo soy un colaborador externo, no esto manteniendo este SDK de forma activa, quizás @Juanii95 o @mminestrelli podrían dar más luz sobre este issue

**Comment by nsabaj95** [comment]
No hay problema.

Espero respuesta de @Juanii95 y @mminestrelli entonces.

**Comment by MercadoPagoDevelopers** [comment]
Hola @nsabaj95,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
