### ISSUE TITLE
Error al generar objeto Payment

### ISSUE THREAD

**Issue by ignacholudela** [mercadopago/sdk-dotnet#77]
El objeto Payment no se genera correctamente si el pago se realizó con "digital_currency".

Esto seguramente se solucionará si se agrega digital_currency como atributo de PaymentTypeId dentro de la clase Common https://github.com/mercadopago/dx-dotnet/blob/master/px-dotnet/Common/PaymentTypeId.cs

**Comment by MercadoPagoDevelopers** [comment]
Hola @ignacholudela,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
