### ISSUE TITLE
Payment not found al hacer Refund

### ISSUE THREAD

**Issue by mg9101** [mercadopago/sdk-dotnet#78]
Necesito realizar un refund desde una aplicación que es MarketPlace, pero me tira el siguiente error
{"message":"Payment not found","error":"not_found","status":404,"cause":[{"code":2000,"description":"Payment not found","data":null}]}

El código es el siguiente:

    MercadoPago.SDK.AccessToken = "access_token_produccion"
    Dim payment As New MercadoPago.Resources.Payment
    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
    payment = MercadoPago.Resources.Payment.FindById("payment_id")
    payment.Refund()
    payment.Save()

El error da en la linea payment.Refund(), lo raro es que antes en el .FindById() ya encontró el pago y puedo ver todos los detalles, pero a la hora de hacer el refund da error. 

Venimos con este error hace rato, lo que impide que se puedan hacer refunds en nuestro marketplace

**Comment by MercadoPagoDevelopers** [comment]
Hola @mg9101 ,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
