### ISSUE TITLE
Error al usar Payment.FindById("payment_id") "No parameterless constructor defined for this object"

### ISSUE THREAD

**Issue by VerloreneSelene** [mercadopago/sdk-dotnet#79]
Al ejecutar Payment.FindById("payment_id") da el siguiente error (de manera intermitente, en algunos casos funciona bien y en otro no, verificando que en todos los casos los ID que envío son correctos.
No parameterless constructor defined for this object
Error Type: MercadoPago.MPException

Stack:
StackTrace:    at MercadoPago.MPBase.ProcessMethod[T](Type clazz, T resource, String methodName, Dictionary`2 parameters, Boolean useCache)
   at MercadoPago.Resources.Payment.FindById(Nullable`1 id)

Eso me da usando un servicio webapi NET 4.5 (que utilizamos para el IPN)

**Comment by fberasategui** [comment]
Me acuerdo que hace un tiempo había un loquito diciendo que usar reflection era una mala idea....

**Comment by MercadoPagoDevelopers** [comment]
Hola @VerloreneSelene ,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
