### ISSUE TITLE
No puedo generar un pre approval de pago recurrente

### ISSUE THREAD

**Issue by lmazzola** [mercadopago/sdk-dotnet#83]
Ejecuto el siguiente codigo para generar un link de pago para una suscripcion recurrente:

                SDK.ClientId = "myClientId";
                SDK.ClientSecret = "myClientSecret";
                Preapproval preapproval = new Preapproval
                {
                    PayerEmail = "testmail@yopmail.com",
                    Reason = "test susbs",
                    BackUrl = "https://mybackurl.com/payment",
                    ExternalReference = "myId",
                    Id = "STARTER",

                    AutoRecurring = new MercadoPago.DataStructures.Preapproval.AutoRecurring
                    {
                        Frequency = 1,
                        FrequencyType = MercadoPago.Common.FrequencyType.months,
                        TransactionAmount = 2,
                        CurrencyId = MercadoPago.Common.CurrencyId.ARS,
                        Start_date = DateTime.Now,
                        End_date = DateTime.Now.AddYears(5)
                    }
                };

                var preapprovalResult = preapproval.Save();

El resultado del save siempre es false y no existen errores

Cuando analizo el request se genera lo siguiente:

POST /preapproval?access_token=APP_USR-XXXXXXXXXXXXXXXX-033109-1b0d7dbb1cdc6a72816f9d630abd3ed8-86893797 HTTP/1.1

{
  "id": "STARTER",
  "reason": "test susbs",
  "payer_email": "testmail@yopmail.com",
  "back_url": "https://testurl.com/payment",
  "auto_recurring": {
    "frequency_type": "months",
    "frequency": 1,
    "transaction_amount": 2.0,
    "currency_id": "ARS",
    "start_date": "2019-03-31T10:33:35.895-03:00",
    "end_date": "2024-03-31T10:33:35.895-03:00"
  },
  "external_reference": "myId"
}

Y la respuesta es:

{"message":null,"error":null,"status":500,"cause":[]}

**Comment by MercadoPagoDevelopers** [comment]
Hola @lmazzola ,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
