### ISSUE TITLE
Compatibilidad para Asp.net Core 2+

### ISSUE THREAD

**Issue by fabrizziocht** [mercadopago/sdk-dotnet#86]
Hola, quisiera solicitar que se creara una versión compatible con Asp.net Core 2+, debido a que netframework te obliga a utilizar servidores windows, los cuales te generan sobrecostos. En un entorno de linux se puede llegar a los mismos resultados.

**Comment by thiagomoises** [comment]
Hola amigo. En algún tiempo estoy trabajando en una versión para .netcore, basada en este proyecto.

[Moises.Toolkit.MercadoPago.NetCore] (https://github.com/thiagomoises/Moises.Toolkit.MercadoPago.NetCore) 

Está incompleto, pero ya es posible manipular clientes, tarjetas y efectuar pagos.
Desafortunadamente no he tenido tiempo de documentar todavía, pero ya es posible utilizar.
Si puedes ayudar contribuyendo, quédate a gusto

**Comment by fberasategui** [comment]
@fabrizziocht olvidate que alguien de MercadoPago te vaya a dar una mano.

@thiagomoises te comento que nosotros ya hicimos [un fork](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk) de este proyecto y lo compilamos contra .NET Standard 2.0, debería correr en .NET Core. Hay un [issue abierto](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk/issues/11) por una incompatibilidad de un paquete de Nuget. Yo no tuve tiempo de arreglar ese problema. Si te parece, estaría bueno que lo tomes, para que se siga trabajando en ese fork en lugar de crear uno nuevo. Tengamos en cuenta que nuestro SDK es casi 100% compatible con el oficial, a nivel de código, con lo cuál la documentación es la misma que la oficial de MercadoPago, y además de eso tiene muchísimas ventajas como por ejemplo soporte para hacer búsquedas a la API de MercadoPago con LINQ y otras cosas.

**Comment by thiagomoises** [comment]
Gracias por la orientación.
Yo ya había estudiado el fork citado, pero no es suficiente para mí por 2 razones:

1 - No nos de la opción de inyección de dependencia, que una de las características del .netcore
2- Imposible utilizar el [Polly](https://github.com/App-vNext/Polly) (Circuit-breaker, Retry, etc).

Pro proyecto que estoy desarrollando si hace necesario estos 2 puntos, entonces para mí se ha hecho más conveniente un desarrollo de cero, siguiendo las características del .netcore.

**Comment by agustinm20** [comment]
Se sabe cuando estará disponible?

**Comment by MercadoPagoDevelopers** [comment]
Hola @fabrizziocht ,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
