### ISSUE TITLE
Permite realizar pago una vez que la orden expiró

### ISSUE THREAD

**Issue by dariocorrea** [mercadopago/sdk-dotnet#88]
Cuando genero una orden y luego el usuario lee el QR, si el usuario ya se encuentra en la opción de Pagar y si la orden expira, puede realizar el pago igualmente.

**Comment by MercadoPagoDevelopers** [comment]
Hola @dariocorrea ,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
