### ISSUE TITLE
Error while tuning Linq QUERY for Payments

### ISSUE THREAD

**Issue by egodein** [mercadopago/sdk-dotnet#91]
Newtonsoft.Json.JsonSerializationException: 'Error converting value "recharge_fee" to type 'System.Nullable`1[MercadoPago.Common.FeeType]'. Path '[11].fee_details[0].type', line 1168, position 30.'

**Comment by egodein** [comment]
I belive that adding the following line to FeeType.cs should fix the problem
        /// <summary> fIX </summary>
        recharge_fee

**Comment by sikamikan** [comment]
why is the documentation of mercadopago so bad?
The documentation of .net SDK is even worst

**Comment by MercadoPagoDevelopers** [comment]
Hi @egodein @sikamikan,

First of all, we would like to give our sincere apologies for our belated answer.

Secondly, we are happy to announce the brand new SDK, which includes most of the suggestions that the community made in this repository. Therefore, all the existing issues and pull requests will be closed.

We are continuously working to keep our code up to date and communicating to you the latest news.

We hope to receive your comments, issues and contributions to keep moving our product to the next level.

Thanks.
The Mercado Pago Developers team.
