### ISSUE TITLE
Customer Not Found Issue

### ISSUE THREAD

**Issue by fatovaring** [mercadopago/sdk-dotnet#92]
Hey all.

Please help me with this issue. My team created an integration with Mercado Pago Argentina and now we cannot test it in the Test Mode environment. The response from Mercado Pago is always the same:

**400 : Customer not found. Causes : 2002 : Customer not found**

The steps that I followed to create the environment:

1. I created an account in Mercado Pago Argentina
2. I took the access token related to the account from step 1, two testing users are created with this token following the next guide: https://www.mercadopago.com.ar/developers/en/guides/payments/web-payment-checkout/test-integration/
3. The test user number 1 is our seller, I logged in in the account with this user for getting the Access Token, Public Key, Client Id y Client Secret, I'm using this information for test the integration.

4. I take the Test user number 2, and I created a new card for him, after this i'm triying to create a payment with this card an user and the response is the next:

**400 : Customer not found. Causes : 2002 : Customer not found**

We checked that the customer is created with the specified id and it is: 
https://api.mercadopago.com/v1/customers/search?access_token=ACCESS_TOKEN

Please help us with this, we already spend two days finding a solution for this.

**Comment by fberasategui** [comment]
do not use 2 users.

**Comment by fatovaring** [comment]
Thanks for your answer. 

What do you mean?
What user should I use? And what user not?

**Comment by MercadoPagoDevelopers** [comment]
Hi @fatovaring ,

First of all, we would like to give our sincere apologies for our belated answer.

Secondly, we are happy to announce the brand new SDK, which includes most of the suggestions that the community made in this repository. Therefore, all the existing issues and pull requests will be closed.

We are continuously working to keep our code up to date and communicating to you the latest news.

We hope to receive your comments, issues and contributions to keep moving our product to the next level.

Thanks.
The Mercado Pago Developers team.
