### ISSUE TITLE
DumpLog can't be disabled

### ISSUE THREAD

**Issue by HerussHub** [mercadopago/sdk-dotnet#94]
Function "MPBase:DumpLog" serializes and writes MPBase object all the time. 

There is no way to disable this feature on release. 

I think this feature should be disabled by default on release. 

There is an overload that can be significant beacause of "System.Diagnostics.Trace.WriteLine" call.

And, maybe, log4net support could be added. 

thanks,

**Comment by MercadoPagoDevelopers** [comment]
Hi @HerussHub ,

First of all, we would like to give our sincere apologies for our belated answer.

Secondly, we are happy to announce the brand new SDK, which includes most of the suggestions that the community made in this repository. Therefore, all the existing issues and pull requests will be closed.

We are continuously working to keep our code up to date and communicating to you the latest news.

We hope to receive your comments, issues and contributions to keep moving our product to the next level.

Thanks.
The Mercado Pago Developers team.
