### ISSUE TITLE
Is the new administration accepting pull requests?

### ISSUE THREAD

**Issue by fberasategui** [mercadopago/sdk-dotnet#97]
Due to [historical reasons](https://github.com/mercadopago/dx-dotnet/pull/55), we have [forked](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk) this SDK.

Maintaining a separate fork creates a lot of overhead for us, mostly because there's almost always a lot of conflicts whenever we try to merge the latest changes from this repo into our own fork.

At this point, there's no denying that our version is greatly superior to the official one in every possible aspect:

  - Better overall architecture (No weird errors like [this](https://github.com/mercadopago/dx-dotnet/issues/79) or [this](https://github.com/mercadopago/dx-dotnet/issues/71) caused by unnecessary use of reflection)
  - C# idiomatic, clean, navigation-friendly (again, no reflection), maintainable codebase.
  - No stack-traversing hacks, no regex-based string parsing, no dictionaries everywhere, no ["stringly-typed"](http://wiki.c2.com/?StringlyTyped) anything.
  - Proper error handling
  - Platform support (.NET Core)
  - Async Support
  - LINQ Support
  - Pre-request validation.
  - Shorter, cleaner, much more developer-friendly resource classes ([this](https://github.com/mercadopago/dx-dotnet/blob/master/px-dotnet/Resources/Payment.cs) vs [this](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk/blob/master/px-dotnet/Resources/Payment.cs))
  - Working CI builds based on Azure Devops.
  - Better user experience (hides internal implementation details that [confuse users a lot](https://groups.google.com/forum/#!category-topic/mercadopago-developers/sdks/jGMV5Bdn8qo))
  - Newer 2.x versions of our fork do not have a dependency on archaic, completely useless .NET 3.5 version from 15 years ago which [no one cares about today](http://www.nemo-docs.com/blog/usage-statistics/). Older versions 1.x still support such a dinosaur if anyone needs it.
  - Properly respects Semantic Versioning by not introducing incompatible, breaking changes in between minor versions.

Also please note that our fork is **100% source compatible** with the official one. Existing consumers would NOT have to refactor their code if they switched to our version

We're willing to contribute these improvements back into the official version if possible, so that we can get rid of the annoying merge conflicts once and for all.

**Comment by MercadoPagoDevelopers** [comment]
Hi @fberasategui ,

First of all, we would like to give our sincere apologies for our belated answer.

Secondly, we are happy to **announce the brand new SDK**, which includes most of the suggestions that the community made in this repository. Therefore, all the existing issues and pull requests will be closed.

We are continuously working to keep our code up to date and communicating to you the latest news.

We hope to receive your comments, issues and contributions to keep moving our product to the next level.

Thanks.
The Mercado Pago Developers team.

**Comment by fberasategui** [comment]
@MercadoPagoDevelopers your copy-pasted reply does not answer my question about pull requests.

I'm glad you guys have finally found out it's not 1999 anymore (at least for anyone not using java), but at this point all my projects that make use of the SDK rely heavily on the LINQ provider I've created, hence in order to stop using the non official version I'd need your version to have feature parity with mine. I'm not willing to rewrite strongly-typed properly architected LINQ queries into a bunch of ridiculous string-based dictionaries.

Please let me know if at the very least, this time you'll pay even the smallest attention to all the hard work I've selflessly contributed (for free), which you basically shit on by letting it rot into oblivion.
